### PR TITLE
Polytope

### PR DESCRIPTION
**Pull request by carterbox**

### CODE REVIEW

**Comment by carterbox** [comment]
@dgursoy, the Travis CI build fails because `wget` cannot successfully download the conda installation script. One way to fix the problem, which I have implemented, is upgrading the build environment to Trusty Tahr. Trusty comes with a more recent version of `wget`, and that solves the failed downloads problem. However, this also means that we can no longer take advantage of container builds because the Trusty images are still in beta. Tried updating the version of `wget` for Precise, but the most recent version you can get is 1.13. Tahr has 1.15.

**Comment by dgursoy** [comment]
Do you want me to go over the code or should I just accept the PR?

**Comment by carterbox** [comment]
I'd like you to investigate why the Travis Build was failing. As far as I can see, the setup for tomopy's Travis Builds is the same, but there was no failure downloading conda.

**Comment by dgursoy** [comment]
I'd say we use it right now, but check in the future if Travis works as expected.

**Pull request merged**
