### PR TITLE
Make demos work

### PR DESCRIPTION
**Pull request by jahomax**

### CODE REVIEW

**Comment by carterbox** [comment]
Hi @jahomax, thanks for fixing these demos. I found an additional demo that needs to be fixed, so could you please check the box on the right side of this pull request that says, "Allow edits from maintainers"?

**Comment by jahomax** [comment]
Hi @carterbox , yes there was an additional demo, but without Anaconda or MKL I couldn't install Tomopy so couldn't fix that one. The "Allow edits from maintainers" box is ticked already it seems.

**Comment by carterbox** [comment]
I figured it out! Thanks for checking on that. Is there a reason that you don't want to use 'conda' for managing your packages and environments?

**Comment by jahomax** [comment]
The reason I use pip is that it comes from python.org's python installer. It's a non-profit organization with no paid components, which is the way I like to operate. I build it from source and it has no propietary-licensed stuff like Intel's MKL.

**Comment by carterbox** [comment]
@jahomax Would you be interested in a build of TomoPy without MKL? It would have reduced functionality.

**Comment by jahomax** [comment]
In principle that would appeal to me, but my tomography work is rather
geometrically different, meaning I can't use standard packages and methods.
But I know of other researchers who like their work to not depend on
non-free licenses.

**Pull request merged**
